export const TEMPLATE_INSTRUCTIONS = [
  ['SIA Sleep Log Template Instructions'],
  [''],
  ['Column', 'Description'],
  ['Date', 'Use YYYY-MM-DD format (e.g., 2026-03-20).'],
  ['Bedtime', 'The time you got into bed or started a sleep segment (HH:mm).'],
  ['Waketime', 'The time you got out of bed or ended a sleep segment (HH:mm).'],
  ['Status_Code', 'Use "SLEEP" for sleep segments and "AWAKE-IN" for time spent awake in bed.'],
  ['SQ', 'Sleep Quality (1-10). Only needed on the first row of each date.'],
  ['R', 'Morning Alertness (1-10). Only needed on the first row of each date.'],
  ['L', 'Daytime Energy Level (1-10). Only needed on the first row of each date.'],
  ['Remarks', 'Any notes about your sleep. Only needed on the first row of each date.'],
  ['Screens_Y', 'yes/no - Did you use digital screens in bed?'],
  ['Stress_1to5', 'Scale 1-5 (1: Calm, 5: High Stress)'],
  ['NaturalWake_Y', 'yes/no - Did you wake up without an alarm?'],
  ['MorningMood_1to5', 'Scale 1-5 (1: Exhausted/Low, 5: Vibrant/High)'],
  ['Sleep_Gadgets', 'Format: gadget_name(durationmin)@timing. Multiple items separated by commas. Valid timings: morning, afternoon, evening. Example: light_therapy(30min)@morning; white_noise; earplugs'],
  [''],
  ['Important Notes:'],
  ['- You can have multiple rows for the same date if you have interrupted sleep.'],
  ['- The system uses a 96-slot ledger (15-min intervals) to process your data.'],
  ['- If you overlap segments, SLEEP takes priority over AWAKE-IN.'],
  ['- If the "Data" sheet is missing, the importer will try to find your data but may route it to unstructured storage.'],
];
